using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchoolManagementSystem.Models
{
    public class Report
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Report Name is required.")]
        [StringLength(100, ErrorMessage = "Report Name cannot exceed 100 characters.")]
        [Display(Name = "Report Name")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please select a report category.")]
        [Display(Name = "Report Category")]
        public string Category { get; set; } = "Financial"; // Financial, Attendance, Enrollment, TeacherWorkload

        [Required]
        [Display(Name = "Date Generated")]
        [DataType(DataType.DateTime)]
        public DateTime GeneratedDate { get; set; } = DateTime.Now;

        [Required]
        [StringLength(50)]
        [Display(Name = "Generated By")]
        public string GeneratedBy { get; set; } = "Admin";

        // Filter Criteria: Saved as JSON string to support dynamic queries
        // Example: { "StartDate": "2026-01-01", "EndDate": "2026-06-28", "ClassId": 3 }
        [Display(Name = "Query Parameters")]
        public string? QueryParametersJson { get; set; }

        // Data Snapshot: Optional field to lock historical table outputs in JSON format.
        // This ensures old statements (like "Tax Year 2025") stay identical even if students are deleted in 2026.
        [Display(Name = "Data Snapshot")]
        public string? DataSnapshotJson { get; set; }

        [StringLength(250, ErrorMessage = "Remarks cannot exceed 250 characters.")]
        public string? Remarks { get; set; }
    }
}